-- Add wallet system tables
CREATE TABLE IF NOT EXISTS wallets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  artistId INT NOT NULL UNIQUE,
  balance INT DEFAULT 0 NOT NULL,
  pendingBalance INT DEFAULT 0 NOT NULL,
  lifetimeEarnings INT DEFAULT 0 NOT NULL,
  status ENUM('active', 'suspended', 'closed') DEFAULT 'active' NOT NULL,
  verificationStatus ENUM('unverified', 'pending', 'verified', 'rejected') DEFAULT 'unverified' NOT NULL,
  currency VARCHAR(3) DEFAULT 'USD' NOT NULL,
  metadata JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (artistId) REFERENCES artist_profiles(id),
  INDEX artist_id_idx (artistId)
);

CREATE TABLE IF NOT EXISTS payment_methods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  walletId INT NOT NULL,
  type ENUM('credit_card', 'debit_card', 'apple_pay', 'venmo', 'zelle', 'cryptocurrency', 'bank_account') NOT NULL,
  provider VARCHAR(50),
  last4 VARCHAR(4),
  expiryMonth INT,
  expiryYear INT,
  brand VARCHAR(50),
  cryptoAddress VARCHAR(255),
  cryptoNetwork VARCHAR(50),
  accountIdentifier VARCHAR(255),
  status ENUM('active', 'inactive', 'expired', 'failed_verification') DEFAULT 'active' NOT NULL,
  isDefault BOOLEAN DEFAULT FALSE NOT NULL,
  verified BOOLEAN DEFAULT FALSE NOT NULL,
  externalId VARCHAR(255),
  externalCustomerId VARCHAR(255),
  metadata JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (walletId) REFERENCES wallets(id),
  INDEX wallet_id_idx (walletId),
  INDEX type_idx (type)
);

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  walletId INT NOT NULL,
  type ENUM('payment', 'tip', 'withdrawal', 'refund', 'payout', 'fee', 'adjustment') NOT NULL,
  amount INT NOT NULL,
  currency VARCHAR(3) DEFAULT 'USD' NOT NULL,
  status ENUM('pending', 'processing', 'completed', 'failed', 'cancelled', 'refunded') DEFAULT 'pending' NOT NULL,
  paymentMethodId INT,
  fromUserId INT,
  toUserId INT,
  orderId INT,
  platformFee INT DEFAULT 0 NOT NULL,
  processingFee INT DEFAULT 0 NOT NULL,
  netAmount INT NOT NULL,
  description TEXT,
  internalNotes TEXT,
  externalId VARCHAR(255),
  externalStatus VARCHAR(50),
  processedAt TIMESTAMP NULL,
  completedAt TIMESTAMP NULL,
  failedAt TIMESTAMP NULL,
  metadata JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (walletId) REFERENCES wallets(id),
  FOREIGN KEY (paymentMethodId) REFERENCES payment_methods(id),
  FOREIGN KEY (fromUserId) REFERENCES users(id),
  FOREIGN KEY (toUserId) REFERENCES users(id),
  FOREIGN KEY (orderId) REFERENCES orders(id),
  INDEX wallet_id_idx (walletId),
  INDEX type_idx (type),
  INDEX status_idx (status),
  INDEX from_user_idx (fromUserId),
  INDEX to_user_idx (toUserId)
);

CREATE TABLE IF NOT EXISTS tips (
  id INT AUTO_INCREMENT PRIMARY KEY,
  transactionId INT NOT NULL UNIQUE,
  fromUserId INT NOT NULL,
  toArtistId INT NOT NULL,
  amount INT NOT NULL,
  currency VARCHAR(3) DEFAULT 'USD' NOT NULL,
  message TEXT,
  isAnonymous BOOLEAN DEFAULT FALSE NOT NULL,
  paymentMethodId INT,
  paymentType VARCHAR(50) NOT NULL,
  status ENUM('pending', 'completed', 'failed', 'refunded') DEFAULT 'pending' NOT NULL,
  platformFee INT DEFAULT 0 NOT NULL,
  processingFee INT DEFAULT 0 NOT NULL,
  netAmount INT NOT NULL,
  completedAt TIMESTAMP NULL,
  metadata JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (transactionId) REFERENCES transactions(id),
  FOREIGN KEY (fromUserId) REFERENCES users(id),
  FOREIGN KEY (toArtistId) REFERENCES artist_profiles(id),
  FOREIGN KEY (paymentMethodId) REFERENCES payment_methods(id),
  INDEX from_user_idx (fromUserId),
  INDEX to_artist_idx (toArtistId),
  INDEX status_idx (status)
);
