import { ENV } from '../_core/env';

/**
 * Send writer invitation email to a co-writer or collaborator
 * Separate file to keep emailService.ts clean and avoid template literal conflicts
 */
export async function sendWriterInvitationEmail(params: {
  recipientEmail: string;
  recipientName: string;
  invitingArtistName: string;
  trackTitle: string;
  splitPercentage: number;
  role: string;
  inviteToken: string;
  baseUrl: string;
}): Promise<void> {
  const inviteUrl = `${params.baseUrl}/writer-invite?token=${params.inviteToken}`;
  const subject = `${params.invitingArtistName} has invited you to a song split on Boptone`;

  const html = [
    '<!DOCTYPE html>',
    '<html>',
    '<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/></head>',
    '<body style="margin:0;padding:0;background:#f5f5f5;font-family:Arial,sans-serif;">',
    '<table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f5;padding:40px 0;">',
    '<tr><td align="center">',
    '<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border:1px solid #e0e0e0;max-width:600px;width:100%;">',
    '<tr><td style="background:#000000;padding:24px 32px;">',
    '<span style="color:#ffffff;font-size:22px;font-weight:900;letter-spacing:2px;text-transform:uppercase;">BOPTONE</span>',
    '</td></tr>',
    '<tr><td style="padding:40px 32px;">',
    '<h1 style="margin:0 0 8px;font-size:24px;font-weight:900;color:#111111;">You have been invited to a song split</h1>',
    `<p style="margin:0 0 24px;font-size:15px;color:#555555;"><strong>${params.invitingArtistName}</strong> has added you as a collaborator on <strong>${params.trackTitle}</strong>.</p>`,
    '<table width="100%" cellpadding="0" cellspacing="0" style="background:#f8f8f8;border:1px solid #e0e0e0;margin-bottom:32px;">',
    '<tr><td style="padding:20px 24px;">',
    '<p style="margin:0 0 4px;font-size:13px;color:#888888;text-transform:uppercase;letter-spacing:1px;">Track</p>',
    `<p style="margin:0 0 16px;font-size:15px;font-weight:700;color:#111111;">${params.trackTitle}</p>`,
    '<p style="margin:0 0 4px;font-size:13px;color:#888888;text-transform:uppercase;letter-spacing:1px;">Your Role</p>',
    `<p style="margin:0 0 16px;font-size:15px;font-weight:700;color:#111111;">${params.role}</p>`,
    '<p style="margin:0 0 4px;font-size:13px;color:#888888;text-transform:uppercase;letter-spacing:1px;">Your Split</p>',
    `<p style="margin:0;font-size:28px;font-weight:900;color:#008B8B;">${params.splitPercentage}%</p>`,
    '</td></tr>',
    '</table>',
    `<p style="margin:0 0 24px;font-size:14px;color:#555555;">By accepting this invitation, you will receive ${params.splitPercentage}% of all streaming royalties and revenue generated by this track on Boptone. Payments are processed automatically.</p>`,
    '<table cellpadding="0" cellspacing="0"><tr>',
    '<td style="background:#000000;padding:14px 32px;">',
    `<a href="${inviteUrl}" style="color:#ffffff;font-size:14px;font-weight:700;text-decoration:none;letter-spacing:1px;text-transform:uppercase;">Accept Invitation</a>`,
    '</td>',
    '</tr></table>',
    `<p style="margin:24px 0 0;font-size:12px;color:#999999;">This invitation expires in 30 days. If you did not expect this email, you can safely ignore it.<br/>Link: <a href="${inviteUrl}" style="color:#008B8B;">${inviteUrl}</a></p>`,
    '</td></tr>',
    '<tr><td style="background:#f8f8f8;padding:20px 32px;border-top:1px solid #e0e0e0;">',
    '<p style="margin:0;font-size:12px;color:#aaaaaa;">Boptone &bull; <a href="https://boptone.com" style="color:#aaaaaa;">boptone.com</a></p>',
    '</td></tr>',
    '</table>',
    '</td></tr>',
    '</table>',
    '</body>',
    '</html>',
  ].join('\n');

  const text = [
    `${params.invitingArtistName} has invited you to a song split on Boptone.`,
    '',
    `Track: ${params.trackTitle}`,
    `Your Role: ${params.role}`,
    `Your Split: ${params.splitPercentage}%`,
    '',
    'Accept your invitation:',
    inviteUrl,
    '',
    'This invitation expires in 30 days.',
  ].join('\n');

  try {
    const response = await fetch(`${ENV.forgeApiUrl}/email/send`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${ENV.forgeApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ to: params.recipientEmail, subject, html, text }),
    });

    if (!response.ok) {
      const error = await response.text();
      console.error('[writerInvitationEmail] Failed to send:', error);
      return;
    }

    console.log(`[writerInvitationEmail] Sent to ${params.recipientEmail} for track "${params.trackTitle}"`);
  } catch (err) {
    console.error('[writerInvitationEmail] Send error:', err);
  }
}
